amzs_menu_system:
  resource: "@AmzsMenuBundle/Resources/config/routes/routes.yaml"
  type: amzs_menu_route_loader
amzs_administrator_setting_bundle:
  resource: "@AmzsSettingBundle/Resources/config/routes/routing.yaml"
  type: amzs_setting_route_loader
amzs_administrator_user_bundle:
  resource: "@AmzsUserBundle/Resources/config/routes/routing.yaml"
  type: amzs_user_route_loader
amzs_admin_topic_bundle:
  resource: "@AmzsTopicBundle/Resources/config/routes/routes.yaml"
  type: amzs_topic_route_loader
amzs_admin_article_bundle:
  resource: "@AmzsArticleBundle/Resources/config/routes/routes.yaml"
  type: amzs_article_route_loader
amzs_admin_page_bundle:
  resource: "@AmzsPageBundle/Resources/config/routes/routes.yaml"
  type: amzs_page_route_loader
#amzs_admin_picture_bundle:
#  resource: "@AmzsPictureBundle/Resources/config/routes/picture.yaml"
#  type: amzs_picture_route_loader
amzs_admin_gallery_bundle:
  resource: "@AmzsGalleryBundle/Resources/config/routes/gallery.yaml"
  type: amzs_gallery_route_loader